name: spacex_launches
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^7.3.1

  # Service Locator
  get_it: ^7.2.0
  injectable: ^1.4.1

  # Navigation
  auto_route: ^3.0.1

  # GraphQL
  graphql_flutter: ^5.0.0

  # UUID
  uuid: ^3.0.4

  # Equality
  freezed_annotation: ^0.14.2
  json_annotation: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.1
  freezed: ^0.14.2
  json_serializable: ^5.0.2
  injectable_generator: ^1.4.1
  auto_route_generator: ^3.0.1
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
